import os
import re

# 1. SETUP: Define the HTML Header and Styles
html_head = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Chinese Song Library</title>
    <style>
        body { font-family: "Segoe UI", "Microsoft YaHei", sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 40px; }
        .container { max-width: 1000px; margin: 0 auto; }
        header { text-align: center; margin-bottom: 50px; }
        h1 { color: #2c3e50; font-size: 2.5em; margin-bottom: 10px; }
        p.subtitle { color: #7f8c8d; font-size: 1.2em; }
        .song-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 25px; }
        .song-card { background: white; border-radius: 12px; padding: 25px; text-decoration: none; color: inherit; box-shadow: 0 4px 15px rgba(0,0,0,0.05); transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s; border: 2px solid transparent; display: flex; flex-direction: column; justify-content: space-between; height: 180px; }
        .song-card:hover { transform: translateY(-5px); box-shadow: 0 10px 25px rgba(52, 152, 219, 0.2); border-color: #3498db; }
        .card-top { display: flex; justify-content: space-between; align-items: flex-start; }
        .song-number { font-size: 3em; font-weight: 900; color: #f0f2f5; line-height: 0.8; }
        .song-info h2 { margin: 0; font-size: 1.3em; color: #2c3e50; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
        .song-info p { margin: 5px 0 0 0; color: #7f8c8d; font-size: 0.95em; }
        .tag { display: inline-block; background-color: #eaf2f8; color: #3498db; padding: 4px 10px; border-radius: 20px; font-size: 0.8em; font-weight: bold; margin-top: 10px; }
        .card-bottom { display: flex; justify-content: flex-end; align-items: center; }
        .btn-text { color: #3498db; font-weight: bold; font-size: 0.9em; }
        .refresh-note { text-align: center; margin-top: 50px; color: #95a5a6; font-size: 0.9em; }
    </style>
</head>
<body>
<div class="container">
    <header>
        <h1>🎵 My Chinese Song Library</h1>
        <p class="subtitle">Deep Dive Vocabulary & Lyrics Study</p>
    </header>
    <div class="song-grid">
"""

html_footer = """
    </div>
    <p class="refresh-note">Generated by build_index.py</p>
</div>
</body>
</html>
"""

# 2. LOGIC: Scan Folder
current_folder = os.getcwd()
files = os.listdir(current_folder)

songs = []

# Regex to match: "1.Chinese Name (English Name).html"
# It handles spaces and different types of parenthesis
pattern = re.compile(r'^(\d+)\s*\.\s*(.+?)\s*[（(](.+?)[)）]\.html$')

for file in files:
    if file.endswith(".html") and file != "index.html":
        match = pattern.match(file)
        if match:
            # We found a song file!
            num = int(match.group(1))
            cn_title = match.group(2).strip()
            en_title = match.group(3).strip()

            songs.append({
                "num": num,
                "cn": cn_title,
                "en": en_title,
                "filename": file
            })

# 3. SORT: Sort by number (1, 2, 3...)
songs.sort(key=lambda x: x["num"])

# 4. BUILD: Generate Card HTML
cards_html = ""
for song in songs:
    # Add a leading zero if number < 10 (e.g., "01")
    display_num = f"{song['num']:02d}"

    card = f"""
        <a href="{song['filename']}" class="song-card">
            <div class="card-top">
                <div class="song-info">
                    <h2>{song['cn']}</h2>
                    <p>{song['en']}</p>
                    <span class="tag">Lesson #{song['num']}</span>
                </div>
                <div class="song-number">{display_num}</div>
            </div>
            <div class="card-bottom">
                <span class="btn-text">Start Learning →</span>
            </div>
        </a>
    """
    cards_html += card

# 5. SAVE: Write the new index.html
with open("index.html", "w", encoding="utf-8") as f:
    f.write(html_head + cards_html + html_footer)

print(f"✅ Success! Found {len(songs)} songs. 'index.html' has been updated.")
